### ISSUE TITLE
VS Code SCM Provider

### ISSUE THREAD

**Issue by seanmcbreen** [stef-levesque/vscode-perforce#41] opened 2017-03-22 20:20 UTC
This is an FYI message - fell free to close....

Hello,

Thanks for creating and extension for VS Code, we have now added an API for VSCode to enable pluggable SCM Providers.  This is currently in the 'preview' state and only in the 'insiders' build.  Our plan is to move this into 'stable' in our next release (early April 17).   

This lays the foundation for rich SCM Extensions to be distributed through the marketplace.  These extensions will have access to all of the features our Git support leverages (this itself is now only using the public API).  

**Our ASK** If you are interested in helping create an SCM provider, we want to help you and have created a new repo with all of the required details including - timelines, instructions, sample implementations, ...   https://github.com/Microsoft/vscode-SCMBuilders

Head on over there if you want to help to get going or to monitor progress - with any luck in the coming months we should have a set of high quality SCM providers for VS Code.

Sean
VS Code Team Member

**Comment by stef-levesque** [comment] 2017-03-22 20:41
Thanks @seanmcbreen , so far I was looking at the Git Extension in the vscode source. 

It's nice to have an official documentation. :+1:

**Comment by stef-levesque** [comment] 2017-03-26 20:10
Work in Progress

![screen shot 2017-03-26 at 4 07 54 pm](https://cloud.githubusercontent.com/assets/7251102/24334774/a4126118-123e-11e7-89a2-7db8aeb3b309.png)

**Comment by seanmcbreen** [comment] 2017-03-26 20:12
Very very cool.  Let us know if you hit any road blocks.

cc @joaomoreno who does all of our Git work and created the API :)

**Comment by stef-levesque** [comment] 2017-03-26 20:46
@joaomoreno it would be nice if we could set our own label to SCMResource.
Supporting [octicon](https://octicons.github.com) icon set, like vscode.StatusBarItem does, could help identify additional informations, like:
* `file opened to previous revision` ![octicon-history](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/history.svg)
* `file needs to be resolved` ![octicon-alert](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/alert.svg)
* `file locked by user` ![octicon-shield](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/shield.svg)

**Comment by joaomoreno** [comment] 2017-03-27 15:31
@stef-levesque Can you file each feature request [in our repo](//github.com/Microsoft/vscode)?

**Comment by stef-levesque** [comment] 2017-03-29 04:43
Is there anyway to know when a SCMResourceGroup is selected? I would like to update the SCMInputBox with the changelist description.

**Comment by joaomoreno** [comment] 2017-03-29 07:31
Interesting. This isn't implemented yet.

**Comment by joaomoreno** [comment] 2017-03-30 07:47
@stef-levesque FYI we're about to push some changes #23645 will which change the API quite a bit. The adoption isn't too big, I hope the comments clarify a bit of what's going on. I'll be here in case you need some help adopting it.

**Comment by joaomoreno** [comment] 2017-03-30 12:43
Another tiny change: Microsoft/vscode#23653

**Comment by joaomoreno** [comment] 2017-03-30 20:38
Hey @stef-levesque. Since a few more changes came in, I decided to write an [adoption guide](https://github.com/Microsoft/vscode-SCMBuilders/wiki/SCM-API-Adoption-Guide). Please let me know if you run into issues, if something isn't clear or you feel something's missing.

**Comment by stef-levesque** [comment] 2017-03-30 20:44
Thanks @joaomoreno, this should make it much easier!

**Comment by stef-levesque** [comment] 2017-04-06 03:39
@seanmcbreen @joaomoreno I am having an issue with submitting the Scm version of the extension.

`window.withScmProgress` has now moved from vscode.proposed.d.ts to vscode.d.ts.
But it is still marked as `proposedApiFunction` in the official 1.11.0 release: 
see [extHost.api.impl.ts](/Microsoft/vscode/blob/1.11.0/src/vs/workbench/api/node/extHost.api.impl.ts#L349)

Now, removing `enableProposedApi` from package.json, the extension throws the following exception:
```
Error: slevesque.perforce cannot access proposed api
    at Object.U.V.o [as withScmProgress] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:362359)
    at Model.<anonymous> (/Users/slevesque/Documents/Projects/vscode-perforce/out/src/scm/Model.js:59:29)
    at next (<anonymous>)
    at fulfilled (/Users/slevesque/Documents/Projects/vscode-perforce/out/src/scm/Model.js:4:58)
```

From my understanding, I cannot publish my extension with `enableProposedApi` in it.

**Comment by stef-levesque** [comment] 2017-04-06 04:28
I would also need a way to change the placeholder text in the ScmInputBox.
I intent to use the box to display and update changelist description, and so should display:
`Description (press Cmd+Enter to create changelist)`
as a placeholder when the default changelist is selected.

**Comment by joaomoreno** [comment] 2017-04-06 08:06
@stef-levesque I've created Microsoft/vscode#24009 for the progress API. We'll get it out asap.

As for the placeholder text, do you mind filing an issue for that?

**Comment by stef-levesque** [comment] 2017-04-06 16:19
Thanks for the quick response.

I create Microsoft/vscode#24090 for the placeholder request

**Comment by seanmcbreen** [comment] 2017-04-06 16:30
We just shipped a build with this fixed :)

**Comment by stef-levesque** [comment] 2017-04-06 16:37
Yes, works fine with 1.11.1

**Comment by stef-levesque** [comment] 2017-04-07 05:09
Just published version 2.0.0 with the beta version of the SCM Provider.

Please, try it and send feedback!

**Closed by stef-levesque** 2017-04-07 05:09 UTC
Labels: enhancement, in progress

**Comment by seanmcbreen** [comment] 2017-04-07 05:28
We are not perforce experts so our testing is a little lame sorry.  I did do a superficial PR for consideration.  Once you feel good about this i.e. have some great end user feedback (which I'm sure you will) we will help promote this e.g. a tweet twitter from _@_code to _@_perforce to help get the word out.  Let us know via here or smcbreen at microsoft.com.

THANK YOU!

**Comment by stef-levesque** [comment] 2017-04-07 05:43
Thanks, I would like to test it more before going more public. I also hope @hoovercj will have time to review the 'Source Depot' compatibility.

There is also a few features I would like before declaring Gold (especially clickable ResourceGroup, drag-and-drop, ...) There is still some work to be done :)

**Comment by seanmcbreen** [comment] 2017-04-07 05:46
Makes total sense - our team is excited so I've seen at least one person notice it I'll ask us to wait a little while.  Again thank you - it's work like this that really make our product a lot better.  

If we can help [recognizing we are not perforce dudes] we will.

**Comment by hoovercj** [comment] 2017-04-07 06:07
Awesome, @stef-levesque! I'll check it out today and if the basics work with SD I'll see if I can get anybody else on my team to give it a go, too.

**Comment by seanmcbreen** [comment] 2017-04-07 06:11
@hoovercj we miss you thanks!

**Comment by hoovercj** [comment] 2017-04-07 09:01
@seanmcbreen <3 - I miss y'all, too!

@stef-levesque unfortunately there are a couple major blockers that prevent this from working as-is with SD. I've opened https://github.com/stef-levesque/vscode-perforce/issues/47

**Comment by stef-levesque** [comment] 2017-04-07 20:34
It seems, with vscode-perforce installed, that Perforce become the default Source Control. This might not be the expected behaviour.

I think that Git should stay the default SCM, unless specified otherwise. Maybe in the User Settings?

**Comment by seanmcbreen** [comment] 2017-04-07 20:54
I agree seems like there should be a setting for default SCM at the workspace level so you don't need to use the UI switcher.

We do want to be able to detect if we should use a provider based on hints e.g. for git any .git* file means default o Git.  Is there something similar for perforce?

@joaomoreno thoughts?

**Comment by hoovercj** [comment] 2017-04-07 21:01
For sd (which will hopefully use the perforce extension) there is a .ini file. I can't speak to actual perforce, though

**Comment by stef-levesque** [comment] 2017-04-07 21:03
For perforce, usually a .p4settings file anywhere in the folder hierarchy. But client settings can also be set globally (environment variables)

**Comment by stef-levesque** [comment] 2017-04-07 22:09
scm.ts
```typescript
export const DefaultSCMProviderIdStorageKey = 'settings.workspace.scm.defaultProviderId';
```
I'm not sure that this value is exposed to the user. 

scmService.ts
```typescript
registerSCMProvider(provider: ISCMProvider): IDisposable {
	this._providers.push(provider);

	const defaultProviderId = this.storageService.get(DefaultSCMProviderIdStorageKey, StorageScope.WORKSPACE);

	if (this._providers.length === 1 || defaultProviderId === provider.id) {
		this.setActiveSCMProdiver(provider);
	}
```

I'm not too sure about the logic of `this._providers.length === 1`. 
If the Perforce extension is quicker to register, and no workspace settings are available, it become de-facto the default.

**Comment by joaomoreno** [comment] 2017-04-10 06:11
@stef-levesque It becomes the active one for this session, but that fact doesn't get stored. We only store the user's preference, when the user himself changes it. If the user has picked Git beforehand, it will be set as the active once it's activated.

In any case we definitely need a story to pick the correct provider for the workspace, based on heuristics.

PS: I just noticed the typo in `setActiveSCMProdiver` 🏄 🌊 😆

**Comment by stef-levesque** [comment] 2017-04-10 17:41
Seems someone need vacations :smirk:
