### ISSUE TITLE
check out (p4 edit) a binary file which is not display-able

### ISSUE THREAD

**Issue by easz** [stef-levesque/vscode-perforce#111] opened 2017-12-07 13:06 UTC
use case:

In my perforce workspace there are some binary files (png, docx, vsdx.,,,) which are not display-able in vscode. However I would still like to make a "perforce edit" within vscode and open it with other program (mspaint, word or visio...)

the use case is not possible. there is no debug output when I try to run "perforce edit".

**Comment by stef-levesque** [comment] 2017-12-07 15:36
VSCode extensions only have visibility over TextDocument tabs. Calling `perforce.edit` on an open Binaries tab results in an error saying `No file selected`. Until VSCode decide to change, there is unfortunately not much we can do.

One way to mitigate that, could be to add some Perforce commands to the Explorer file context menu (`add`, `edit`, ...). Although, in order to not overcrowd the context menu, most commands would only be accessible from the Source Control viewlet (`revert`, `move to changelist`, ...)

**Comment by easz** [comment] 2017-12-08 07:29
Putting commands into context menu (one single perforce entry with commands in sub menu?) would be probably not a bad idea.

**Comment by stef-levesque** [comment] 2017-12-08 15:40
Then I'll close this issue, as a duplicate of #37 
I'll try to push it in next release

**Closed by stef-levesque** 2017-12-08 15:40 UTC
Labels: help wanted, vscode
