### ISSUE TITLE
perforce.editOnFileSave appears to be successful, but error message is still shown

### ISSUE THREAD

**Issue by ihalip** [stef-levesque/vscode-perforce#61] opened 2017-04-19 16:23 UTC
OS: Linux Mint 18.1
vscode: Version 1.11.2
vscode-perforce: 2.0.1

Other extensions: ms-vscode.cpptools, msjsdiag.debugger-for-chrome, dbaeumer.vscode-eslint, eg2.tslint

I have "perforce.editOnFileSave": true and when I make a simple modification (like adding a newline) into a file that is not checked out, it will be checked out into the default changelist as expected. I can see the change I made when I check the diff.

However, vscode still shows a message saying the file is write-protected:
![image](https://cloud.githubusercontent.com/assets/1991437/25190679/aa0d2774-2535-11e7-9b02-0008127d9a67.png)

**Comment by stef-levesque** [comment] 2017-04-19 16:31
cc @jel-massih

**Comment by TheHolyWaffle** [comment] 2017-04-26 10:00
"perforce.editOnFileSave": true also gives me an error but the operation is NOT successful. 

For now, a workaround is to use "perforce.editOnFilemodified": true

**Comment by jel-massih** [comment] 2017-05-03 23:24
Yeah I think something might have changed in a recent update, I am getting this occasionally.

It might be a bit before I can take a look at this, have been pretty swamped lately.

**Comment by stef-levesque** [comment] 2017-12-17 23:20
Close as duplicate of #110

**Closed by stef-levesque** 2017-12-17 23:20 UTC
Labels: help wanted
