### ISSUE TITLE
Not clearing changelists after submit, if no open files

### ISSUE THREAD

**Issue by nomaed** [stef-levesque/vscode-perforce#82] opened 2017-08-09 14:33 UTC
Seems like after submitting a changelist, if no open files remain, the old changelist/files are "stuck" in the source control list.

Looking at the output, there's
```
"/usr/local/bin/p4" opened 
ERROR:
File(s) not opened on this client.
```
Probably when an error occurs, the list isn't updated.

If I open any other file manually, `p4 opened` returns a list of files (well, 1 file at this point) and the list of open files is refreshed then correctly.
But then if I revert that one opened file, the same problem occurs: it's stuck forever in the list, because `p4 opened` returns an error.

Also, I am pretty sure I've seen this issue of `p4 opened` errors being discussed somewhere, but I can't find it o.O

**Comment by nomaed** [comment] 2017-08-09 14:37
Ah, found the original comment I was referring to:
https://github.com/stef-levesque/vscode-perforce/issues/62#issuecomment-312480112
In a little different context.

By the way, plugin version is 2.1.1

**Comment by stef-levesque** [comment] 2017-12-17 23:22
Closing as duplicate of #62

**Closed by stef-levesque** 2017-12-17 23:22 UTC
Labels: bug
